apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-sns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-sns:v1.7.0
