apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: credentials
  # LocalStack endpoint configuration
  endpoint:
    url:
      type: Static
      static: http://host.docker.internal:4510
    hostnameImmutable: true
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  s3_use_path_style: true
