apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
